// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1--rc1
// source: workerMngr.proto

package pb_workerMngr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MatchReq) Reset() {
	*x = MatchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workerMngr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchReq) ProtoMessage() {}

func (x *MatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_workerMngr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchReq.ProtoReflect.Descriptor instead.
func (*MatchReq) Descriptor() ([]byte, []int) {
	return file_workerMngr_proto_rawDescGZIP(), []int{0}
}

type MatchResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchId     string `protobuf:"bytes,1,opt,name=matchId,proto3" json:"matchId,omitempty"`
	TourId      string `protobuf:"bytes,2,opt,name=tourId,proto3" json:"tourId,omitempty"`
	FstPlayerID string `protobuf:"bytes,3,opt,name=FstPlayerID,proto3" json:"FstPlayerID,omitempty"`
	SndPlayerID string `protobuf:"bytes,4,opt,name=SndPlayerID,proto3" json:"SndPlayerID,omitempty"`
}

func (x *MatchResp) Reset() {
	*x = MatchResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workerMngr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchResp) ProtoMessage() {}

func (x *MatchResp) ProtoReflect() protoreflect.Message {
	mi := &file_workerMngr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchResp.ProtoReflect.Descriptor instead.
func (*MatchResp) Descriptor() ([]byte, []int) {
	return file_workerMngr_proto_rawDescGZIP(), []int{1}
}

func (x *MatchResp) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *MatchResp) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *MatchResp) GetFstPlayerID() string {
	if x != nil {
		return x.FstPlayerID
	}
	return ""
}

func (x *MatchResp) GetSndPlayerID() string {
	if x != nil {
		return x.SndPlayerID
	}
	return ""
}

type ResultReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchId     string `protobuf:"bytes,1,opt,name=matchId,proto3" json:"matchId,omitempty"`
	TourId      string `protobuf:"bytes,2,opt,name=tourId,proto3" json:"tourId,omitempty"`
	FstPlayerID string `protobuf:"bytes,3,opt,name=FstPlayerID,proto3" json:"FstPlayerID,omitempty"`
	SndPlayerID string `protobuf:"bytes,4,opt,name=SndPlayerID,proto3" json:"SndPlayerID,omitempty"`
	Winner      uint32 `protobuf:"varint,5,opt,name=winner,proto3" json:"winner,omitempty"` // 1, 2, 3: Winner 1, 2 or Tie
}

func (x *ResultReq) Reset() {
	*x = ResultReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workerMngr_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultReq) ProtoMessage() {}

func (x *ResultReq) ProtoReflect() protoreflect.Message {
	mi := &file_workerMngr_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultReq.ProtoReflect.Descriptor instead.
func (*ResultReq) Descriptor() ([]byte, []int) {
	return file_workerMngr_proto_rawDescGZIP(), []int{2}
}

func (x *ResultReq) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *ResultReq) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *ResultReq) GetFstPlayerID() string {
	if x != nil {
		return x.FstPlayerID
	}
	return ""
}

func (x *ResultReq) GetSndPlayerID() string {
	if x != nil {
		return x.SndPlayerID
	}
	return ""
}

func (x *ResultReq) GetWinner() uint32 {
	if x != nil {
		return x.Winner
	}
	return 0
}

type ResultResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResultResp) Reset() {
	*x = ResultResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workerMngr_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultResp) ProtoMessage() {}

func (x *ResultResp) ProtoReflect() protoreflect.Message {
	mi := &file_workerMngr_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultResp.ProtoReflect.Descriptor instead.
func (*ResultResp) Descriptor() ([]byte, []int) {
	return file_workerMngr_proto_rawDescGZIP(), []int{3}
}

var File_workerMngr_proto protoreflect.FileDescriptor

var file_workerMngr_proto_rawDesc = []byte{
	0x0a, 0x10, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x4d, 0x6e, 0x67, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0d, 0x70, 0x62, 0x5f, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x4d, 0x6e, 0x67,
	0x72, 0x22, 0x0a, 0x0a, 0x08, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x22, 0x81, 0x01,
	0x0a, 0x09, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x75, 0x72, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f, 0x75, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a,
	0x0b, 0x46, 0x73, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x46, 0x73, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x12,
	0x20, 0x0a, 0x0b, 0x53, 0x6e, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x53, 0x6e, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x44, 0x22, 0x99, 0x01, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x75,
	0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f, 0x75, 0x72, 0x49,
	0x64, 0x12, 0x20, 0x0a, 0x0b, 0x46, 0x73, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x46, 0x73, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x6e, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x53, 0x6e, 0x64, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x22, 0x0c, 0x0a,
	0x0a, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70, 0x32, 0x91, 0x01, 0x0a, 0x0a,
	0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x4d, 0x6e, 0x67, 0x72, 0x12, 0x3f, 0x0a, 0x0a, 0x47, 0x69,
	0x76, 0x65, 0x4d, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x5f, 0x77, 0x6f,
	0x72, 0x6b, 0x65, 0x72, 0x4d, 0x6e, 0x67, 0x72, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65,
	0x71, 0x1a, 0x18, 0x2e, 0x70, 0x62, 0x5f, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x4d, 0x6e, 0x67,
	0x72, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x12, 0x42, 0x0a, 0x0b, 0x43,
	0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x2e, 0x70, 0x62, 0x5f,
	0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x4d, 0x6e, 0x67, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x70, 0x62, 0x5f, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72,
	0x4d, 0x6e, 0x67, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70, 0x42,
	0x12, 0x5a, 0x10, 0x2e, 0x2e, 0x2f, 0x70, 0x62, 0x5f, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x4d,
	0x6e, 0x67, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_workerMngr_proto_rawDescOnce sync.Once
	file_workerMngr_proto_rawDescData = file_workerMngr_proto_rawDesc
)

func file_workerMngr_proto_rawDescGZIP() []byte {
	file_workerMngr_proto_rawDescOnce.Do(func() {
		file_workerMngr_proto_rawDescData = protoimpl.X.CompressGZIP(file_workerMngr_proto_rawDescData)
	})
	return file_workerMngr_proto_rawDescData
}

var file_workerMngr_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_workerMngr_proto_goTypes = []interface{}{
	(*MatchReq)(nil),   // 0: pb_workerMngr.MatchReq
	(*MatchResp)(nil),  // 1: pb_workerMngr.MatchResp
	(*ResultReq)(nil),  // 2: pb_workerMngr.ResultReq
	(*ResultResp)(nil), // 3: pb_workerMngr.ResultResp
}
var file_workerMngr_proto_depIdxs = []int32{
	0, // 0: pb_workerMngr.WorkerMngr.GiveMeWork:input_type -> pb_workerMngr.MatchReq
	2, // 1: pb_workerMngr.WorkerMngr.CatchResult:input_type -> pb_workerMngr.ResultReq
	1, // 2: pb_workerMngr.WorkerMngr.GiveMeWork:output_type -> pb_workerMngr.MatchResp
	3, // 3: pb_workerMngr.WorkerMngr.CatchResult:output_type -> pb_workerMngr.ResultResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_workerMngr_proto_init() }
func file_workerMngr_proto_init() {
	if File_workerMngr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_workerMngr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workerMngr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workerMngr_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workerMngr_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_workerMngr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workerMngr_proto_goTypes,
		DependencyIndexes: file_workerMngr_proto_depIdxs,
		MessageInfos:      file_workerMngr_proto_msgTypes,
	}.Build()
	File_workerMngr_proto = out.File
	file_workerMngr_proto_rawDesc = nil
	file_workerMngr_proto_goTypes = nil
	file_workerMngr_proto_depIdxs = nil
}
