version: "3.9"
services:
  server:
    build:
      context: ./server
      dockerfile: server.Dockerfile
    ports:
      - "8080:8080"
    networks:
      - project_network
  client:
    build:
      context: ./client
      dockerfile: client.Dockerfile
    networks:
      - project_network
    depends_on:
      - server
networks:
  project_network:
    driver: bridge
