// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1--rc1
// source: ring.proto

package pb_ring

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RingClient is the client API for Ring service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RingClient interface {
	SendMessage(ctx context.Context, in *ElectionMsgReq, opts ...grpc.CallOption) (*ElectionMsgResp, error)
	GetLeader(ctx context.Context, in *GetLeaderReq, opts ...grpc.CallOption) (*GetLeaderResp, error)
}

type ringClient struct {
	cc grpc.ClientConnInterface
}

func NewRingClient(cc grpc.ClientConnInterface) RingClient {
	return &ringClient{cc}
}

func (c *ringClient) SendMessage(ctx context.Context, in *ElectionMsgReq, opts ...grpc.CallOption) (*ElectionMsgResp, error) {
	out := new(ElectionMsgResp)
	err := c.cc.Invoke(ctx, "/pb_ring.Ring/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ringClient) GetLeader(ctx context.Context, in *GetLeaderReq, opts ...grpc.CallOption) (*GetLeaderResp, error) {
	out := new(GetLeaderResp)
	err := c.cc.Invoke(ctx, "/pb_ring.Ring/GetLeader", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RingServer is the server API for Ring service.
// All implementations must embed UnimplementedRingServer
// for forward compatibility
type RingServer interface {
	SendMessage(context.Context, *ElectionMsgReq) (*ElectionMsgResp, error)
	GetLeader(context.Context, *GetLeaderReq) (*GetLeaderResp, error)
	mustEmbedUnimplementedRingServer()
}

// UnimplementedRingServer must be embedded to have forward compatible implementations.
type UnimplementedRingServer struct {
}

func (UnimplementedRingServer) SendMessage(context.Context, *ElectionMsgReq) (*ElectionMsgResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedRingServer) GetLeader(context.Context, *GetLeaderReq) (*GetLeaderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLeader not implemented")
}
func (UnimplementedRingServer) mustEmbedUnimplementedRingServer() {}

// UnsafeRingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RingServer will
// result in compilation errors.
type UnsafeRingServer interface {
	mustEmbedUnimplementedRingServer()
}

func RegisterRingServer(s grpc.ServiceRegistrar, srv RingServer) {
	s.RegisterService(&Ring_ServiceDesc, srv)
}

func _Ring_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ElectionMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RingServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb_ring.Ring/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RingServer).SendMessage(ctx, req.(*ElectionMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ring_GetLeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeaderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RingServer).GetLeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb_ring.Ring/GetLeader",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RingServer).GetLeader(ctx, req.(*GetLeaderReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Ring_ServiceDesc is the grpc.ServiceDesc for Ring service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ring_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb_ring.Ring",
	HandlerType: (*RingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _Ring_SendMessage_Handler,
		},
		{
			MethodName: "GetLeader",
			Handler:    _Ring_GetLeader_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ring.proto",
}
