// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1--rc1
// source: ring.proto

package pb_ring

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ElectionMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type uint32   `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	OnIt []string `protobuf:"bytes,2,rep,name=on_it,json=onIt,proto3" json:"on_it,omitempty"`
}

func (x *ElectionMsgReq) Reset() {
	*x = ElectionMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ring_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElectionMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElectionMsgReq) ProtoMessage() {}

func (x *ElectionMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_ring_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElectionMsgReq.ProtoReflect.Descriptor instead.
func (*ElectionMsgReq) Descriptor() ([]byte, []int) {
	return file_ring_proto_rawDescGZIP(), []int{0}
}

func (x *ElectionMsgReq) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ElectionMsgReq) GetOnIt() []string {
	if x != nil {
		return x.OnIt
	}
	return nil
}

type ElectionMsgResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ElectionMsgResp) Reset() {
	*x = ElectionMsgResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ring_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElectionMsgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElectionMsgResp) ProtoMessage() {}

func (x *ElectionMsgResp) ProtoReflect() protoreflect.Message {
	mi := &file_ring_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElectionMsgResp.ProtoReflect.Descriptor instead.
func (*ElectionMsgResp) Descriptor() ([]byte, []int) {
	return file_ring_proto_rawDescGZIP(), []int{1}
}

type GetLeaderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetLeaderReq) Reset() {
	*x = GetLeaderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ring_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLeaderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderReq) ProtoMessage() {}

func (x *GetLeaderReq) ProtoReflect() protoreflect.Message {
	mi := &file_ring_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderReq.ProtoReflect.Descriptor instead.
func (*GetLeaderReq) Descriptor() ([]byte, []int) {
	return file_ring_proto_rawDescGZIP(), []int{2}
}

type GetLeaderResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LeaderAddr string `protobuf:"bytes,1,opt,name=leaderAddr,proto3" json:"leaderAddr,omitempty"`
}

func (x *GetLeaderResp) Reset() {
	*x = GetLeaderResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ring_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLeaderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderResp) ProtoMessage() {}

func (x *GetLeaderResp) ProtoReflect() protoreflect.Message {
	mi := &file_ring_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderResp.ProtoReflect.Descriptor instead.
func (*GetLeaderResp) Descriptor() ([]byte, []int) {
	return file_ring_proto_rawDescGZIP(), []int{3}
}

func (x *GetLeaderResp) GetLeaderAddr() string {
	if x != nil {
		return x.LeaderAddr
	}
	return ""
}

var File_ring_proto protoreflect.FileDescriptor

var file_ring_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x72, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x62,
	0x5f, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x39, 0x0a, 0x0e, 0x45, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x6f,
	0x6e, 0x5f, 0x69, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6f, 0x6e, 0x49, 0x74,
	0x22, 0x11, 0x0a, 0x0f, 0x45, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x73, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x0e, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x22, 0x2f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x41, 0x64,
	0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x41, 0x64, 0x64, 0x72, 0x32, 0x84, 0x01, 0x0a, 0x04, 0x52, 0x69, 0x6e, 0x67, 0x12, 0x40, 0x0a,
	0x0b, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x17, 0x2e, 0x70,
	0x62, 0x5f, 0x72, 0x69, 0x6e, 0x67, 0x2e, 0x45, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4d,
	0x73, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x70, 0x62, 0x5f, 0x72, 0x69, 0x6e, 0x67, 0x2e,
	0x45, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x3a, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x15, 0x2e, 0x70,
	0x62, 0x5f, 0x72, 0x69, 0x6e, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x5f, 0x72, 0x69, 0x6e, 0x67, 0x2e, 0x47, 0x65,
	0x74, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0c, 0x5a, 0x0a, 0x2e,
	0x2e, 0x2f, 0x70, 0x62, 0x5f, 0x72, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_ring_proto_rawDescOnce sync.Once
	file_ring_proto_rawDescData = file_ring_proto_rawDesc
)

func file_ring_proto_rawDescGZIP() []byte {
	file_ring_proto_rawDescOnce.Do(func() {
		file_ring_proto_rawDescData = protoimpl.X.CompressGZIP(file_ring_proto_rawDescData)
	})
	return file_ring_proto_rawDescData
}

var file_ring_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ring_proto_goTypes = []interface{}{
	(*ElectionMsgReq)(nil),  // 0: pb_ring.ElectionMsgReq
	(*ElectionMsgResp)(nil), // 1: pb_ring.ElectionMsgResp
	(*GetLeaderReq)(nil),    // 2: pb_ring.GetLeaderReq
	(*GetLeaderResp)(nil),   // 3: pb_ring.GetLeaderResp
}
var file_ring_proto_depIdxs = []int32{
	0, // 0: pb_ring.Ring.SendMessage:input_type -> pb_ring.ElectionMsgReq
	2, // 1: pb_ring.Ring.GetLeader:input_type -> pb_ring.GetLeaderReq
	1, // 2: pb_ring.Ring.SendMessage:output_type -> pb_ring.ElectionMsgResp
	3, // 3: pb_ring.Ring.GetLeader:output_type -> pb_ring.GetLeaderResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ring_proto_init() }
func file_ring_proto_init() {
	if File_ring_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ring_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElectionMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ring_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElectionMsgResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ring_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLeaderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ring_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLeaderResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ring_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ring_proto_goTypes,
		DependencyIndexes: file_ring_proto_depIdxs,
		MessageInfos:      file_ring_proto_msgTypes,
	}.Build()
	File_ring_proto = out.File
	file_ring_proto_rawDesc = nil
	file_ring_proto_goTypes = nil
	file_ring_proto_depIdxs = nil
}
